# Generated by Django 5.2.7 on 2025-10-07 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_mobile_money', 'MTN Mobile Money')], max_length=40)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('numero_ticket', models.CharField(default=uuid.uuid4, max_length=12, unique=True)),
                ('paye', models.BooleanField(default=False)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
