# Generated by Django 5.2.7 on 2025-10-22 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_reference_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
